hubot-scripts.json

obtiene información sobre :beer: de la api de brewerydb. necesita
API-KEY (entregada a :hector: para que la agregue a heroku)

[new] brewerydb.coffee

---

package.json
scripts/tusecreto.js

Queda pendiente incluir un "#X no está entre los canales permitidos".  https://github.com/slackhq/hubot-slack/issues/361 hace algo complicado distinguir si el usuario está usando la palabra o está nombrando el canal.
Una vez que no se coma los # se podría incluir, aparte de poder usar regex directo en vez de usar el array para distinguir el canal.
resolves #68

feat(tusecreto): add optional channel param

---

hubot-scripts.json
scripts/recetas.js
scripts/torrent.js

- Se corrigió orden y formato de enlaces de resultados en torrent
- Se cambio `console.log` por `robot.emit` en torrent
- Se agrego `unfurl_links` en los resultados de receta y torrent
- Se elimino `hubot-scripts.json`. #132

Se corrigió orden y formato de enlaces en script torrent

---

scripts/larger.js
scripts/portadas.coffee

test: `huemul larger devschile.cl`
cata—

Nuevo, obtiene info sobre una url de larger.io

---

package.json

Ahora es posible usar texto arriba y abajo usando la sintaxis:
`huemul meme generate <template-name> <text1>|<text2>`
También es posible seguir usando la vieja sintaxis, para solo tener texto inferior:
`huemul meme generate <template-name> <text>`
Agradecimientos a :alvaro: :clap:

feat(scripts): Se actualizo script hubot-memegeneration

---

scripts/bip.coffee
scripts/cuantovale.js

test: `huemul cuantovale be-studios.com`
cata—

bugfix: split `-` for URL's fixed

---

.travis.yml
package.json
scripts/karma.coffee
test/karma.test.coffee

Uso anteriormente:
```
<= usuario1++ usuario2++
=> solo usuario 1 recibe karma
```
Uso con este cambio:
```
<= usuario1++ usuario2++ usuario3-- blabla usuario4++
=> usuario1, usuario2, usuario4, reciben karma
=> usuario3 pierde karma
```

Permitir mas de un usuario por linea al asignar karma

---

.travis.yml
external-scripts.json
package.json

Hay dos diseños:
Full
Short
Por defecto es el diseño full, pero se puede cambiar estableciendo la variable de entorno TRAVIS_SHORT=true
El icono de travis es random entre 15 diseños oficiales distintos

Se agrego webhook para recibir notificaciones de travis

---

scripts/karma.coffee

Hice los tests y corren todos, en teoría debería enviar el mensaje como DM al que invocó a _huemul_ 
ping @juanbrujo @lgaticaq @gmq @hectorpalmatellez

Conflicto de nombres enviado por privado a usuario

---

bin/hubot

Creo que esto corrige a :huemul:, leyendo un .env dentro del contenedor docker de dokku, en otro formato del esperado

fix(env): Se quito lectura de .env

---

scripts/portadas.coffee

El departamento de "_ta madre, se pone a codear en Montevideo_" les presenta la adenda para los diarios dentro del paraguas de Medios Regionales
Incluye desambiguación en el listado (por la coincidencia de El Mercurio con los 3 diarios que comparten ese nombre) y diversos casos de acentuación ("Crónica Chillán", por ejemplo)
`huemul portada la estrella de arica`
`huemul portada mercuriovalpo`
`huemul portada hxh`
/cc @lgaticaq @juanbrujo

Agregamos las publicaciones de Medios Regionales

---

scripts/portadas.coffee

En Hoyxhoy existe un producto comercial, llamado "portada falsa". Como no carga la portada correcta en la ruta asignada en estos casos, usamos un endpoint (visible, en JSON) que informa la portada real

fix(portadas): Corregimos cómo tomamos portada de Hoyxhoy

---

scripts/error-handler.js

Es necesario configurar la variable de entorno `SENTRY_DSN`

Se agrego enviar errores a Sentry

---

test/portadas.test.js

En salida de `ava` se mostraba un `console.log` del test de portadas, y se eliminaron los caracteres innecesarios de la url `img`

Removido caracteres innecesarios en la url y un console.log

---

scripts/orionx.js

Habian campos que no se usaban en la consulta, asi que solo deje `price` de esta forma se ahorran un par de _ms_

Pequeña optimizacion para obtener el precio en orionx

---

CONTRIBUTING.md
docker-compose.yml

Necesario para los huemul developers que solo usan bases de datos con docker. Ya que ahora es necesario tener mongo escuchando peticiones para levantar huemul en dev.

Se agrego docker-compose.yml para levantar mongo en dev

---

scripts/portadas.js

- agregamos las portadas de Copesa directo desde su plataforma
- ajustamos cómo se lee el json de hoyxhoy, gentileza de una decisión comercial
:perrosleep:

fix(portadas): portadas Copesa, ajuste para HxH

---

package.json
yarn.lock

Se actualiza la lib [bip](https://github.com/lgaticaq/bip) para solucionar el error de obtener saldos negativos

fix(deps): update bip to v3.0.2

---

scripts/calendario.js
test/calendario.test.js

Estos son los nuevos comandos:
```
hubot calendario
hubot calendario diciembre
hubot calendario mayo 2018
hubot calendario diciembre 1989
```
El script solo funciona entre 1582 (inclusión del calendario gregoriano) y el año actual + 100 años como sugirio @inawrath 
solves #432

extend calendar functionality to support month and year selection

---

scripts/portadas.js

Ya que ahora el aviso de portada falsa no se va a actualizar seguido, agregamos método para cargar la página 3 (que es la portada editorial, cuando hay portada falsa) con un comando
Por cierto, qué lindo que les interese el diario :')

fix(portadas): Agregamos modo para forzar página en hoyxhoy

---

scripts/flipper.js

El kl le puso `www` y la respuesta viene sin `www` así que tampoco iba a funcionar solo cambiando la URL:
* http://www.tableflipper.com/json

fix(tableflipper) fix urls and response to display gifs

---

scripts/saluda.js

Slack ahora manda el evento de `enter` apenas se invita al usuario asi que el evento ya no trae el name o incluso el id, por eso fallaba.

fix(saluda): arregla saludo a usuarios nuevos

---

scripts/karma.js
test/karma.test.js

Arregla detallitos fatales
- Hay un usuario eliminado en la base de datos que mataba el filter
- Ahora usa el id para comparar el usuario que modificar el karma con el target
- Agregar una última linea de defensa si es que el usuario no tiene ni display name o real name (_creo_ que no debería pasar... excepto cuando el usuario está borrado)

Karma final final

---

CODEOWNERS

La idea es que se asignen automáticamente revisores a los PRs dependiendo de que archivos se tocan. Mas info [aquí](https://help.github.com/en/github/administering-a-repository/enabling-required-reviews-for-pull-requests)

Se agrega CODEOWNERS

---

scripts/twitter.js

Hay un _typo_ en la URL que hace que los enlaces no funcionen.

fix(twitter-feed): url typo

---

.github/PULL_REQUEST_TEMPLATE.md

Buscando mas info de plantillas solo logre dar con que todos los ejemplos usan el nombre por defecto de la plantilla. Lo cual significa que solo es posible usar una sola plantilla ara todos los PRs.
Adicionalmente la cabecera anterior solo es valida para plantillas de issues así que la saque.

Se renombra plantilla de pull request al por defecto

---

scripts/uoct-golden.js
test/uoct-golden.test.js

- Se corrige el ordenamiento de los eventos de más nuevos a más viejos.
- Se agrega delay manual (500ms) a los tests para evitar errores random producto de `race condition`.

Se corrige orden de eventos en uoct

---

CODEOWNERS
scripts/covid19.js

Se agrega script que entrega la cantidad de casos confirmados, recuperados y muertes por el corona virus en Chile.
@hectorpalmatellez++ por el link de la api.
CLI
```
> huemul coronavirus
> Hay 43 casos confirmados, 0 recuperados y 0 muertes en Chile
```
Slack

feat(scripts): add covid19 resume

---

scripts/poll.js

Status messages are now ephemeral so as to not clutter the  channel with errors.

HOTFIX(poll.js): Status messages are now ephemeral

---

scripts/portadas.js

- removed El Tipógrafo (Rancagua don't exist anyway).
- re-added La Tercera and La Cuarta from kiosko.net.
$ huemul portada la tercera
huemul> http://img.kiosko.net/2020/08/03/cl/cl_tercera.750.jpg
$ huemul portada la cuarta
huemul> http://img.kiosko.net/2020/08/03/cl/cl_cuarta.750.jpg

fix(js): removed deprecated. renew 2 newspapers URLs

---

scripts/horario-verano.js
scripts/temblor.js

test: 
```
huemul> huemul horario verano inicio
huemul> :alarm_clock: El horario de verano este 2020 comienza el domingo 06-09-2020 a las 00:00hrs.
```
test:
```
huemul> huemul temblores costa rica
huemul>
M 6.0 - 3 km ESE of Jacó, Costa Rica: 
- Lugar: 3 km ESE of Jacó, Costa Rica 
- Magnitud: 6 (richter) 
- Fecha/Hora: Mon Aug 24 2020 18:51:10 GMT-0300 (Chile Summer Time) 
- Enlace: https://earthquake.usgs.gov/earthquakes/eventpage/us7000bcbv
```

fix(js): summertime starts sunday am, not saturday pm

---

README.md
scripts/pegas.js
test/pegas.test.js

Fix de script ya que getonbrd cambio de `.cl` a `.com` y de `empleos-` a `jobs-`, se asen internacionales.
```
> huemul pegas junior
Buscando en GetOnBrd... :dev:
Se han encontrado 150 resultados para *junior*:
1: <https://www.getonbrd.com/jobs/programming/ingeniero-en-desarrollo-react-tcit-santiago|Ingeniero Node.js React (Junior) - Full time>
2: <https://www.getonbrd.com/jobs/mobile-developer/ios-mobile-software-engineer-modernizing-medicine-santiago|iOS Mobile Software Engineer - Full time>
3: <https://www.getonbrd.com/jobs/design-ux/disenador-ux-leytonmedia-santiago|Diseñador(a) UX - Full time>
4: <https://www.getonbrd.com/jobs/programming/technical-lead-shopify-denda-santiago|Desarrollador en Shopify - Full time>
5: <https://www.getonbrd.com/jobs/programming/full-stack-developer-mystr …
```

fix(js): change query domain to search jobs

---

scripts/rae.js

La RAE no tiene API oficial para solicitar la definición de una palabra, tampóco encontré alguna otra API que haga esto.
Este script usa la URL pública para buscar una palabra en su página `https://dle.rae.es/srv/search?w=palabra` y con la ayuda de cheerio extrae el contenido de la defincion de un meta tag del html.
Cuando no se ha encontrado palabra el mismo web scrap devuelve siempre el mismo contenido:
`Versión electrónica 23.4 del «Diccionario de la lengua española», obra lexicográfica académica por excelencia.`
Por lo que usé la primera palabra `Versión` como indicador para una palabra no existente o incorrecta.
Se uso node-fetch en vez del robot http request. Si esto es problemático puedo intentar cambiarlo.
Comandos: define|rae
@Huemul define extravagante
`1. adj. Que se hace o …

Script que pide definción de palabra desde la RAE

---

scripts/gardel.js

Se agrega mensaje específico para "cuando pagan" en caso de que hayan pagado y siga cursando el mes. Soluciona https://github.com/devschile/huemul/issues/706
Asumiendo para el ejemplo que el Último día hábil del mes es el próximo 28 de Octubre.
```
// Corriendo el 29 de Octubre (Singular días despues)
huemul> huemul cuando pagan
huemul> Pagaron hace un día. Este mes el pago fue el 28, el pasado viernes
// Corriendo el 31 de Octubre (Plural días despues)
huemul> huemul cuando pagan
huemul> Pagaron hace 3 días. Este mes el pago fue el 28, el pasado viernes
// Corriendo el 28 de Octubre (No cambios)
huemul> huemul cuando pagan
huemul> :tada: Hoy pagan :tada:
// Corriendo el 18 de Ocutbre (No cambios)
huemul> huemul cuando pagan
huemul> Faltan 10 días para que paguen. Este mes pagan el 28, …
```

fix(gardel): show explicit message for past days

---

package.json
scripts/justwatch.js
yarn.lock

Permite saber el proveedor y acceder a más info en la página de JustWatch
Resuleve: https://github.com/devschile/huemul/issues/707
```
// TV Show Found  
huemul> huemul donde ver mr robot
huemul> Puedes ver Mr. Robot en: Amazon Prime Video, Movistar Play
Puedes ver más info en la página de JustWatch: https://www.justwatch.com/cl/serie/mr-robot
// Movie Found
huemul> huemul donde ver la comunidad del anillo
huemul> Puedes ver El señor de los anillos: La comunidad del anillo en: Apple iTunes, Google Play Movies, HBO Go, Amazon Prime Video, Movistar Play, HBO Max
Puedes ver más info en la página de JustWatch: https://www.justwatch.com/cl/pelicula/el-senor-de-los-anillos-la-comunidad-del-anillo
// No found
huemul> huemul donde ver dhamer
huemul> No he podido encontrar sugerencia para dhamer. …
```

feat(justwatch): include justwatch-api interaction to check providers

---

scripts/justwatch.js

- Permite usar tilde para buscar `dónde ver` una película 
- Permite usar `ver` parbuscar una película
```
huemul> huemul dónde ver mr robot
huemul> Puedes ver Mr. Robot en: Amazon Prime Video, Movistar Play
Puedes ver más info en la página de JustWatch: https://www.justwatch.com/cl/serie/mr-robot
huemul> huemul donde ver mr robot
huemul> Puedes ver Mr. Robot en: Amazon Prime Video, Movistar Play
Puedes ver más info en la página de JustWatch: https://www.justwatch.com/cl/serie/mr-robot
huemul> huemul ver mr robot
huemul> Puedes ver Mr. Robot en: Amazon Prime Video, Movistar Play
Puedes ver más info en la página de JustWatch: https://www.justwatch.com/cl/serie/mr-robot
```

feat(justwatch): allow use dónde ver / donde ver / ver

---

scripts/polenes.js

Permite saber el estado de los polenes de Santiago conectandose a http://www.polenes.cl/index.asp
```
huemul> huemul polenes
huemul> Período: lunes, 24 de octubre de 2022 al domingo, 30 de octubre de 2022
Total Arboles: (66 g/m3)
Plátano Oriental: (18 g/m3)
Pastos: (42 g/m3)
Malezas: (8 g/m3)
Comentarios: Niveles  ALTOS. Los principales pólenes detectados fueron los de pastos.
Predicciones: Niveles  ALTOS los principales pólenes detectados serán los de pastos. El plátano oriental registrará un descenso significativo.
Recomendaciones: Evite tenderse en el pasto o cortar este personalmente. Mantenga las ventanas de su habitación y las del auto cerradas la mayor parte del tiempo. Use anteojos de sol y mascarillas en exteriores. En caso de síntoma persistentes consulte a su médico.
Puedes ver …
```

feat(polenes): add polenes script to get polen info

---

scripts/discord.js
test/discord.test.js

Retorna el link al discord de devs chile con un link que no expira. 
Proporcione un snippet indicando un ejemplo del comportamiento.
Ejemplo:
```
> huemul discord
> Aquí tienes el link al discord de devsChile: https://discord.gg/dKmPnpu5rY
```

feat(discord): retorna el link a discord de devschile

---

scripts/gardel.js

Agrega opción de definir un día específico como día de pago, reemplazando la lógica de `último día hábil del mes`. Si este día definido cae en finde: mala suerte.
Día definido que ya pasó.
Día definido en el futuro

feat(gardel): add custom payday option

---

scripts/gardel.js
test/gardel.test.js

Se corrige regex para que se pueda usar `huemul gardel 25`, solo funcionaba con `huemul cuando pagan 25`.
Ademas se corrige la captura del argumento `param`.

fix(gardel): fix regex and get param

---

CODEOWNERS
scripts/fechas-importantes.js
test/fechas-importantes.test.js

Fix que mitiga las conversiones erróneas a NaN, undefined e Invalid date usando el script fechas importantes.
- Matcher actualizado para obtener la fecha requerida desde el mensaje del usuario
- Pasar la fecha como string directamente a MomentJS para su parsing.
- Unit tests básicos para detección de NaN, undefined o Invalid Date en todas las fechas soportadas

fix(fechas-importantes): Mitigar respuestas NaN, undefined, invalid date
