devschile/huemul

package.json

`huemul generate mufasa que pasa mufasa`
`huemul template add hipnosapo 101010101`
`huemul generate hipnosapo ando pal sapo`

Se agrego comando para agregar nuevas plantillas y se cambio el de generar memes

---

external-scripts.json
package.json

Se agrego version de hubot-wikipedia multilenguaje y se actualizo hubot-memegenerator

---

external-scripts.json
package.json

`huemul fmg domains` -> `Obtiene listado de dominios disponibles`
`huemul fmg watch <email>` -> `Queda a la espera de un nuevo email`
Se recomienda ejecutar ambos comandos en privado al señor Huemul

Se agrego hubot-fmg (FakeMailGenerator)

---

scripts/finvox.coffee

el simbolo elegido para :huemul:-coin es ℌℭ (ojalá renderice bien)

huemulcoin agregado

---

package.json
scripts/clima.js
scripts/nasa.js

Obtiene info del clima desde donde el usuario haga la consulta, la
manda a Wttr.in y muestra el resultado en Slack.

nuevo :sunny: :rainbow: :cloud:

---

scripts/clima.js

ademas resultado pasa como source a ver si se muestra mejor.

ciudad como argumento | default: Santiago

---

external-scripts.json
package.json

desde https://github.com/juanbrujo/hubot-onemi/

nuevo: hubot-onemi

---

scripts/agencias.coffee

Add proposed images to `agencias` script/command

---

scripts/concurso.js

test. necesito saber el output de esto.

---

scripts/concurso.js

lo siento el prueba/error …
:thinking_face:

dejando a :jorge: nomás como user a ver si anda.

---

scripts/concurso.js

ahora publica en #comunidad

---

scripts/gardel.js
scripts/proximo-feriado.js

Para saber cuántos días faltan para el próximo feriado en Chile, cuál es y de qué tipo.

Próximo feriado

---

package.json
scripts/github-status.coffee

ligera mejora en script, nueva version en npm

nueva version hubot-beerjs

---

scripts/vaporwave.coffee

Convierte un texto a formato ｖａｐｏｒｗａｖｅ

vaporwave text

---

package.json

Se implemento *attachments* para entregar la respuesta de multiples resultados de forma colapsada

Update hubot-info-rut to v1.0.4

---

package.json

:hector: cuando/si aceptas el PR de hubot-cpf, hay que mergear esta
nueva versión. no olvides actualizarlo en NPM

Update Master && upgrade hubot-cpf

---

README.md

reemplazada imagen del animal que se dañó

nueva selfie de :huemul:

---

package.json
scripts/torrent.js

- new library, bypass cloud flare 5 secs site access.
- output fixed, link auto-added
test: `hubot torrent whathever`

fixed cloudflare block

---

scripts/bola8.js

test: `huemul pregunta viviré estas fiestas patrias?`

nuevo script aconsejador

---

scripts/pegas.js

merge de master y nuevo script para buscar pegas

---

scripts/pegas.js

además se me pasaron unos console.log() :retard: :dev: jorgee++

enlaces mejorados

---

scripts/gardel.js

Mejoras varias

---

public/css/agencias.css
public/js/agencias.js
scripts/gardel.js
views/agencias.pug

ayer si aporta y no me pitee nada :/ :leonardo: puedes echarle un ojo
principalmente a agencias.js?

dándole colorsh a lo hecho por :leonardo: merge master y mejora output agencias/all

---

views/agencias.pug

se me había olvidado poner este divcito el pug hehe

mejor orden de btns

---

package.json

Actualizado hubot-info-rut

---

package.json

Corregido el :bug: que no mostraba los resultados

chore(package): Update hubot-info-rut

---

external-scripts.json
package.json

Se agrego notificación de nuevos deploy de :pudu:

feat(scripts): Add hubot-heroku-deploy-hook

---

public/css/agencias.css

se pueden verificar en: https://huemul.herokuapp.com/agencias/

varias mejoras CSS a dashboard gif's agencias

---

scripts/kendrick.coffee

Anna Kendrick Script

---

scripts/karma.coffee

No logre testear esto pero es una solución para el problemas de los nuevos usuarios con el karma

fix(karma): Se agrego almacenar usuario la primera vez que ingresa

---

scripts/global420.js
scripts/match.js
scripts/rut.js

test: `hubot match male | female`

Muchas mejoras y nuevo script 

---

scripts/match.js

ES6 to ES5 porque :huemul: :thumbsdown:

---

scripts/match.js

test: `huemul match male|female`

mejora: se agrega el nombre del match

---

scripts/match.js

require: moment
test: huemul match male|female
pd. cata—

agregado la edad de la persona a matchear

---

scripts/votador.coffee

test:
```
huemul inicio votador hola, mundo
huemul voto 1
huemul conteo votador
huemul fin votador
```

mejoras en el despliegue de texto y resultados

---

scripts/proximo-feriado.js

test: `huemul próximo feriado`

enhancement: added date to output and typo mistakes

---

scripts/proximo-feriado.js

test: `huemul proximo feriado`
pd. cata—*1000

enhancement: humanised output

---

scripts/pegas.js

test: `huemul pega en front`
pd. nicolascine—
cata— por no valor estos esfuerzos para que tengamos una mejor
comunidad :crying_cat_face:

fixed: getonbrd changed markup and cheerio :boom:

---

scripts/pegas.js
scripts/regalador.js

nuevo script sugeridor de regalos

---

package.json
scripts/knasta.js

test: `huemul knasta smart tv`

nuevo: busca productos en Knasta.cl

---

package.json
scripts/knasta.js

feat: better output (price + discount)

---

package.json
scripts/knasta.js

feat: back link + price + discount

---

scripts/knasta.js

antes tomaba las sugerencias a pesar de no tener resultado
test:
- tiene: `huemul knasta smart tv`
- no tiene: `huemul knasta liashlo`

feat: ahora entrega resultados vacíos si los hay

---

scripts/proximo-feriado.js

esto venía malo del _slack anterior_ :sadpudu:
pd. jorge++

bugfix: victor ql pasaba el mes como el día :wntartd:

---

external-scripts.json
package.json
scripts/larger.js

2 nuevos commits

---

scripts/lmgtfy.coffee

test: `huemul google devschile`

update: mejor emoji y cambio de animal

---

scripts/votador.coffee

test: `huemul inicio votador hola,chao`

feat: mejor texto de intro con instrucciones

---

external-scripts.json
package.json
scripts/votador.coffee

test: `huemul mercadolibre pistola agua`

nuevo script hubot-mercadolibre_cl

---

scripts/cuantovale.js

test: `huemul cuantovale devschile.cl`

nuevo: Obtiene el valor de un sitio usando su URL a través de worthofweb.com

---

scripts/bip.coffee
scripts/cuantovale.js
scripts/dameunaclave.coffee

test: `Huemul Bip 08360996`
test: `huemul cuantovale be-studios.com`
test: `huemul dame una clave 12`

change API BIP && better output Dame Una Clave && better split for composite domains

---

scripts/votador.coffee

test:
- `huemul inicio votador uno,dos,tres`
- `huemul voto 1`
- `huemul fin votador`

mejora: muestra porcentaje de votaciones

---

external-scripts.json
package.json

Comando: `hubot kitsu <anime>`

feat(scripts): Se agrego hubot-kitsu para obtener info sobre animes

---

scripts/nosvimoh.coffee

despídase con estilo, no sea ordinario

NOS VIMO CABRO

---

scripts/karma.coffee
test/karma.test.coffee

Eliminadas las posibilidades erróneas como más de dos _dashes_ entre otros. 
**demo:** https://regex101.com/r/rXY0ID/1

Karma regex 

---

scripts/imdb.coffee

– Actualizado para nuevo formato de respuesta de la API
– Simplificado en base al uso habitual
– Nuevo atributo `year` para búsquedas más específicas
– Nuevo valor *Awards*

Actualización y mejora del script IMDb:

---

scripts/beneficios.js
scripts/bola8.js
scripts/lmgtfy.coffee
test/NaN.test.coffee
test/alegria.test.coffee
test/beneficios.test.coffee
test/bola8.test.coffee
test/citas.test.coffee
test/guruguru.test.coffee
test/invierte.test.coffee
test/kendrick.test.coffee
test/lmgtfy.test.coffee
test/nosvimoh.test.coffee
test/pinera.test.coffee
test/ql.test.coffee
test/que_almorzar.coffee

Los scripts beneficiados son: NaN, alegria, beneficios, bola8, citas, guruguru, invierte, kendrick, lmgtfy, nosvimoh, pinera, ql, que_almorzar

Se agregaron mas tests

---

.travis.yml
external-scripts.json
package.json

Se agrego hubot-dokku-hook para notificar el deploy

---

external-scripts.json
package.json

Se agrego hubot-buscandriu

---

package.json

Ahora esta mejor el resultado en teléfonos

Se actualizo hubot-buscandriu a v0.0.2

---

scripts/gold.js

Comandos:
- `huemul gold insert <key>`
- `huemul gold status <name>`

Se agrego comando para poder usar las :monea: keys filtradas

---

README.md

Se agrego badges de dependencias #189

---

scripts/knasta.js

test: `huemul knasta macbook pro touchbar`

fix(scrapper): removida clase weona que se me quedó

---

scripts/calendario.js
scripts/concurso.js

nuevo: calendario mes actual

---

scripts/portadas.coffee

Además, agregamos `hxh` a la etiqueta del Hoyxhoy

(fix) portadas: Reducimos tamaño portadas (de 1440 a 550) en MR

---

scripts/votador.coffee

(chore)votador: Cambiamos las menciones, de hubot a huemul

---

app.json

Ya me respondieron de dokku y no hay dramas en agregar un app.json solo con la parte del script para crear los hooks.
Mas info [acá](https://github.com/dokku/dokku/pull/2698)

Se agrego postdeploy con delay para que :huemul: alcance a despertar

---

scripts/nosvimoh.coffee

pa que :hector: deje de presionar

Update nos vimo

---

package.json

update(version): new hubot-onemi version

---

scripts/proximo-feriado.js

Se quito sumar 1 día al calcular diferencia de días

---

scripts/temblor.js

https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&minmagnitude=6

terremotos desde U.S Geological Survey

---

scripts/gold.js

Se agrego metodo para verificar status desde cualquier script con `robot.golden.isGold(user)`
Se corrigio mensaje en status
Se elimino variable sin uso en list

feat(gold): Se agrego comando para eliminar usuarios

---

scripts/noticias.js
test/noticias.test.js

filtrar noticias repetidas

---

test/temblores.test.js

fix(test): a ver si anda el de temblores ahora

---

package.json
scripts/temblor.js
test/temblores.test.js
yarn.lock

Temblores con attachments

---

package.json
scripts/gmq.js
yarn.lock

feat(gmq): Feliz cumpleaños :gmq:

---

scripts/nosvimoh.coffee

Un amable mensaje cuando quedas harto de tanto #llanto

chore(nosvimoh): Agregamos nuevo GIF, a petición del público

---

scripts/multas-empresa.js

Script destinado para revisar si la agencia a la que se va a postular es _best place to work_.
Comando `huemul multas-empresa <rut>`
Primera version solo informa si posee o no, no las lista en caso de tener

Se agrego script para consultar multas de empresas

---

scripts/karma.js
test/karma.test.js

-Se permite quitar karma a uno mismo :retard: . Idea entregada por :vforvicente:

Se permite quitar karma a uno mismo

---

package.json
scripts/golden-escorts.js

new(script): solo para golden :monea:

---

scripts/golden-escorts.js
scripts/saluda.coffee

chore(txt): better text

---

scripts/error-handler.js
scripts/word-blacklist.js

Se cambio notificación a canal de dedicado (SENTRY_CHANNEL), ya seteado
Se corrigió comparación en word-blacklist.js

Fix sentry

---

package.json
yarn.lock

Corrige responder el request del webhook

Se actualizo hubot-sentry-integration a la version v0.0.2

---

package.json

new: mrrobot is coming!

---

scripts/portadas.js
test/portadas.test.js

El dominio `www.portadaschilenas.com` TAMALO así que todas las portadas dependientes de ese dominio fueron dadas de baja

Se quitaron portadas del dominio www.portadaschilenas.com

---

scripts/pegas.js
test/html/pegas-200.html
test/pegas.test.js

Ademas se agrego captura de errores y mock de responses

Se agrego unfurl_links en pegas

---

scripts/proximo-feriado.js

JSON actualizado con los feriados legales de Chile.

Cambio de url al JSON con los feriados legales de Chile

---

scripts/portadas.js

test:
```
huemul portada la cuarta
huemul portada el mercurio
huemul portada lun
```

chore(js): 3 nuevos diarios nacionales

---

scripts/portadas.js

Para que @juanbrujo no se compre un MacBook Pro nuevo cada mañana

fix(portadas): Agregamos cachebreaker a portadas Medios Regionales

---

scripts/tupoto.js

Comandos
- hubot tupo.to _URL_
- hubot tupoto _URL_
- hubot tupotoizame _URL_
- hubot tupotizame _URL_

Simple tupo.to

---

scripts/tupoto.js

Se corrige error al acortar urls desde :huemul:

fix(tupoto): se agrego header application/json

---

package.json
scripts/imdb.js

test: `huemul imdb the martian`

fix(api): new API endpoint, previous one ￼

---

scripts/imdb.js

test: `huemul movie the thing`

chore(js): api key removida a .env

---

scripts/imdb.js

test:
- `huemul movie star wars`
- `huemul serie dexter`

chore(js): separado output de películas / series

---

scripts/proximo-feriado.js

test: `huemul proximo feriado`

fix(js): weekDays arreglado :qls: 

---

scripts/finvox.js

chore(finvox): add eth to currencies

---

scripts/forvo-golden.js

test:
```
huemul pronuncia pene
huemul pronuncia pico
huemul pronuncia vida
huemul pronuncia ñoqihw1
```

new(js): obtiene resultados de pronunciación de una palabra/término/concepto de forvo.com

---

package.json
scripts/assimov.js
scripts/steam.js

Hola amigos,
Acabo de agregar dos scripts para huemul con lo siguiente:
> huemul steam daily
muestra la oferta del día en steam
> huemul ley robot/bot 
muestra las tres leyes robóticas según asimov
@lgaticaq @juanbrujo @gmq @hectorpalmatellez 
*A ver* si mas adelante actualizo el de steam para que muestre mas ofertas o especiales, Saludos.

steam deal daily, el robot by Isaac Asimov

---

scripts/steam.js

@lgaticaq @juanbrujo @gmq ahí agregué la cookie con la locación de chile según tu sugerencia, para que lo prueben cuando puedan.
saludos y buen fin de semana

add new cookie steam chile

---

scripts/steam.js

agregué un par de cosas al cookie para ver si se arregla el tema de la conversión en plata chilena...
@lgaticaq @gmq @juanbrujo

se modifica cookie agregando mas datos y timezone por si las moscas

---

scripts/steam.js

- const all the things
- better command handle, if moved to a broader scope
- some typo fixes
test:
`huemul steam` -> error msg
`huemul steam lala` -> error msg
`huemul steam daily` -> returns offer

chore(js): several code improvements

---

scripts/forvo-golden.js

Es un WIP de como agregar pronunciación es mas idiomas del PR enviado ayer por @juanbrujo 
Agradezco cualquier feedback!

Agregar pronunciación e más idioma

---

scripts/portadas.js

chore(portada): nuevo diario Folha de São Paulo (Brasil)

---

scripts/quozio.js

El script permite generar quote image desde quozio
El comando es `hubot quozio <user> dijo <quote>`

feat(scripts): se agrego script quozio

---

package.json

test: `huemul meli dildo 13 pulgadas`

fix(version): major update mercadolibre lib

---

scripts/uoct-golden.js

test: `huemul uoct|taco|tr(aá)nsito`

new(script): trae data de tránsito de la uoct

---

scripts/uoct-golden.js

fix(js): missing > for slack output

---

scripts/uoct-golden.js

fix(js): :wntard:

---

scripts/shows-countdown.js

Utiliza [https://www.tvmaze.com/api](https://www.tvmaze.com/api) buscar series y obtener datos del siguiente episodio.
Comandos:
* huemul countdown <title>

new(script): Retorna tiempo restante para el próximo episodio de una serie

---

scripts/finvox.js
scripts/karma.js

fixes: https://github.com/devschile/huemul/issues/271
test:
```
huemul finvox help
huemul finvox dolar|usd
huemul finvox uf
huemul finvox euro
huemul finvox ipc
huemul finvox utm
huemul finvox huemulcoin
```

fix(js): new API source

---

scripts/finvox.js

test:
```
huemul finvox bitcoin
huemul finvox dolar
```

fix(js): bitcoin bug smashed

---

package.json

test:
```
huemul surbtc bitcoin
huemul surbtc ethereum
```

new version hubot-surbtc

---

scripts/coinmarketcap.js

`huemul cmc ripple`
`huemul coinmarketcap neblio`

feat(scripts): retrieve data from coinmarketcap

---

scripts/coinmarketcap.js
scripts/karma.js

test:
- `huemul coinmarketcap neblio`
- `huemul coinmarketcap htmlcoin`
*I’ll fix karma later

feat(num): better currency output

---

scripts/karma.js
scripts/theme.js

test:
- `https://huemul.devschile.cl/huemul/karma/log`
- `https://huemul.devschile.cl/huemul/karma/log/claudrocker`

chore(design): better theme output for karma

---

scripts/wallets.js

* `huemul wallet eth`
* `huemul wallet BTC`
* `huemul wallet help`

feat(script): list crypto currency wallets to receive donations

---

scripts/torrent.js
test/torrent.test.js

test: `huemul torrent Harry Potter`

fix(source): now get results from YIFI YTS

---

scripts/portadas.js

test:
`huemul portada el país uruguay`
`huemul portada el país españa`

fix(typo): accents added

---

package.json
scripts/torrent.js
test/torrent.test.js

test:
```
huemul surbtc bitcoin
huemul surbtc btc
huemul surbtc eth
huemul surbtc blah
```

update(fix): fixes some bugs

---

scripts/clima.js
scripts/noticias.js
test/clima.test.js
test/html/clima-200-1.html
test/html/clima-200-2.html
test/html/clima-500.html
test/html/recetas-200.html
test/karma.test.js
test/noticias.test.js
test/recetas.test.js
test/torrent.test.js

Se agrego mock a test de recetas, torrent y clima
Se corrigió error en scripts clima y noticias

Se agregó mock a varios test

---

package.json

test:
```
huemul surbtc Bitcoin
huemul surbtc BTC
```

new(version): updated surbtc due small fix

---

scripts/orionx.js

Uso sigue igual solo se cambio el endpoint de a consulta

feat(orionx): se cambio consulta a api para obtener solo el último precio

---

external-scripts.json
package.json
yarn.lock

new(script): earth impact monitor system

---

external-scripts.json
package.json
yarn.lock

new(script): hubo-chaucha added

---

scripts/invierte.js

fix(char): p->d

---

scripts/portadas.js

test:
```
huemul portada el tipógrafo
huemul portada el tipografo de rancagua
```

new(portada): tipografo de rancagua added

---

scripts/orionx.js
test/orionx.test.js

La variable de entorno ya fue seteada

feat(orionx): se agrego enviar timestamp, apikey y signature

---

scripts/orionx.js
test/orionx.test.js

Se agrego variable de entrono ORIONX_ENDPOINT (ya agregada en dokku)
Se corrigió hash de hmac a sha512

fix(orionx): se corrigió consulta a api

---

scripts/thicc.js

𠘨乇山(丂匚尺工尸丅): 卂刀刀 丅乇乂丅 丅口 丅卄工匚匚 丂匚尺工尸丅

---

package.json
scripts/vuelos-baratos.js

Cree una aplicación externa para poderle dar mejor soporte al scraping de vuelos

fix vuelo script

---

scripts/nosvimoh.js

Add image to nosvimo script

---

package-lock.json
scripts/steam.js

Se eliminó la consulta de especiales, reemplazándola por consulta de juegos, la cual muestra algunos datos generales de este, su valor y descripción, ademas de su descuento si aplica.
@gmq @lgaticaq @hectorpalmatellez 
<= TEST =>
```
huemul> huemul steam CELESTE
huemul> Nombre del Juego: Celeste
Valor: $CLP *9500*
Descripción: Help Madeline survive her inner demons on her journey to the top of Celeste Mountain, in this super-tight platformer from the creators of TowerFall. Brave hundreds of hand-crafted challenges, uncover devious secrets, and piece together the mystery of the mountain. <https://store.steampowered.com/app/504230|Ver más>
```

nuevos comandos al script de steam

---

scripts/steam.js

fix steam help

---

scripts/steam.js

puro amor a huemul <3
@lgaticaq @gmq

bug fixes de los juegos con valor 0 y otros ajustes al script

---

scripts/steam.js

Si hizo más legible el código, se quitaron el new Promise en donde no era necesario y se agrego try/catch al parsear json.

Refactor de steam

---

.gitignore
scripts/karma.js

Se simplifica el recuperar y transformar el karma para mejorar el rendimiento

Mejorar rendimiento de karma

---

scripts/karma.js

Perdón :gmq: se me paso cambiar el nombre de la variable

fix(karma): se corrige nombre de variable :see_no_evil:

---

scripts/clima.js
test/dameunatarjeta.test.js
test/html/dameunatarjeta-200.html

Se eliminaron los garabatos

---

scripts/math.js

@here terrible longis

---

scripts/math.js

jaime-- TAMALO

---

external-scripts.json
package.json
yarn.lock

Se añade script para que huemul traduzca un mensaje a jerigonza 
https://www.npmjs.com/package/hubot-jerigonza

Adding hubot-jerigonza

---

scripts/steam.js

huemul> huemul steam hotline miami
huemul> Nombre del Juego: *Hotline Miami*
Valor: *CLP $1.375* (%75 Off)
Desarrollador: * Dennaton Games *
Editor: * Devolver Digital *
Metacritic: *85*
Fecha del Lanzamiento: *23 Oct, 2012*
Género: *Action, Indie*
Descripción: Hotline Miami is a high-octane action game overflowing with raw brutality, hard-boiled gunplay and skull crushing close combat. <https://store.steampowered.com/app/219150|Ver más>
huemul>

fix del error 302 que redireccionaba la petición

---

package.json
yarn.lock

Se cambia indice del match en el regex

Fixing match index in response

---

scripts/math.js
scripts/steam.js

@gmq @lgaticaq @hectorpalmatellez

fix de valores free-to-play & seteo de info

---

scripts/pegas.js
test/pegas.test.js

chore(js): better result output

---

package.json
scripts/bip.js
yarn.lock

Se cambio fuente de datos y se cambio formato de respuesta

---

scripts/bip.js

Se corrige lectura con números con cero a la izquierda

---

scripts/proximo-feriado.js

:ya: ahora si. Me taldie y no agregue ese archivo en el commit anterior.
```bash
huemul> huemul proximo feriado
huemul> El próximo feriado es el *Lunes 2 de Julio*, quedan *21* días. Se celebra: San Pedro y San Pablo (_religioso_).
```

Se corrigió zona horaria

---

scripts/dameunkeldor.js

new(script): display a random :keldor:

---

scripts/18.js

new(script): cuanto falta pal 18 de sedtiembre

---

package.json
scripts/correos.js
yarn.lock

Se agrega mejora la respuesta de la consulta

feat(correos): se cambia scrapping por lib correos-chile

---

scripts/correos.js

fix(correos): fix get last event

---

scripts/orionx.js

feat(orionx): agrega luka

---

scripts/dameunaexcusa.js

test: `huemul dame una excusa`

new script

---

scripts/clima.js

fix(clima): remove all wrong characters

---

scripts/temblor.js

TAWENO, fixea esto https://github.com/devschile/huemul/issues/447

chore(js): better instructions && display max. 5 results

---

scripts/quefumar.js
scripts/temblor.js

fix(js): .slice(0, 5) en slack environment

---

scripts/calendario.js
scripts/gardel.js
scripts/word-blacklist.js

Prettier aplico formato en el archivo `scripts/calendario.js` yo no fui

fix(patterns): add flag case insensitive

---

package.json
scripts/dameunbackend.js
scripts/horoscopo.js
yarn.lock

test: `huemul dame un backend`

new(script)

---

scripts/karma.js
test/karma.test.js

fix(karma): excepciones excplícitas para el karma (p.ej, c++)

---

scripts/rut.js
test/rut.test.js

```bash
huemul> huemul dame un rut empresa
huemul> Un RUT: 78.410.069-3
huemul> huemul dame un rut persona
huemul> Un RUT: 13.150.457-8
huemul> huemul dame un rut
huemul> Un RUT: 13.150.457-8
```

Se agrega soporte a rutjs para obtener rut de empresa

---

scripts/noticias.js
test/noticias.test.js

Se cambia fuente de noticias a ahoranoticias

---

scripts/noticias.js

fix(noticias): fix parse title

---

scripts/saluda.js

Se cambia canal a escuchar evento enter

Se corrige script saludo

---

scripts/map.js

En el ejemplo la dirección se transforma en un link con la url a google maps

feat(map): add slack format

---

scripts/dameundinosaurio.js

Added new file for huemul dame un saurio

---

scripts/horoscopo.js

fix(horoscopo): add title

---

scripts/dameunafortuna.js

test: `huemul dame una fortuna`

new(script): entrega una frase de galleta de la fortuna

---

scripts/gmq.js
scripts/theme.js

fixes #494 
Los otros cambios fueron hechos por prettier

replace rawgit with jsdelivr as rawgit is shutting down

---

scripts/calendario.js
test/calendario.test.js

Tuve que cambiar dos cosas:
- estaba enviando dos `msg.send` y habian ocasiones en las que el segundo aparecia primero :retard:
- la respuesta del huemul contenia el mismo texto que triguereaba el script. Nunca lo tuve en cuenta

fix bug in calendar

---

scripts/dameunloto.js

La idea es aumentar la cantidad de :patrones: del slack

feat: new loto script

---

.travis.yml
package.json

BREAKING CHANGE: Drop support to node v8

feat(node): set min node version to v10

---

package.json
yarn.lock

fix(deps): update hubot-info-rut to v4.0.0

---

scripts/slack-actions.js
scripts/votador.js

Permite a cualquier script dentro de huemul usar elementos interactivos.
Lo que hace Slack cuando se presiona un botón es mandar un callback a `http://<url-del-bot>/slack-actions`. Este script convierte ese callback en un evento y así el script correspondiente puede recibir el payload del callback con `robot.on('nombre-del-callback')`
Los botones del votador son más que nada un proof of concept de lo que se puede hacer, no le dedique mucho tiempo.

feat(slack): agrega ruta para callbacks de slack

---

scripts/vuelos-baratos.js

mainly to avoid despegar's previsualization

refactor: little changes to improve readability

---

scripts/siglas.js

test: `huemul siglas Héctor feo`

new(script): Siglas a un nombre / palabra

---

scripts/siglas.js

feat(siglas): better output

---

scripts/pegas.js
test/pegas.test.js

chore(js): fixed output

---

package.json
yarn.lock

update(lib): new version fixed hubot-nic_chile

---

scripts/year-progress.js

Aqui agrego el comando year progress, la creacion de la barra la copie de bot de twitter
#524  
Este es mi primer aporte, quedo atento a sus comentarios

Year progress

---

scripts/year-progress.js

test: 
‘huemul year progress’
‘huemul como vamos’
‘huemul cómo vamos’

chore(js): output improvement

---

scripts/18.js

Con el codigo anterior era necesario modificar cada año la fecha del 18, ahora es dinamica

Mejore script con fecha dinamica para el 18

---

scripts/enelespacio.js

El script tenia varios send por lo que hacia que saliera el titulo desordenado.
Error:
Fix:

Corrigiendo orden del output en el comando en el espacio

---

scripts/enelespacio.js

La solucion de generar un array e ir agregando los mensajes no funciono, seguian saliendo desordenados, ahora se genera un string con saltos de linea

Ahora el mensaje se manda como un string con saltos de linea

---

scripts/awesome.js

Se corrige mostrar links

---

scripts/map.js

bugfix(map): add marker to map

---

scripts/map.js

[**Enlace a mapa**](https://www.google.com/maps?q=44.7440364%2C-94.7152067&t=m&z=12)

fix(map): use cordinates for locations

---

scripts/citas.js
test/citas.test.js

feat(citas): better output

---

scripts/lavin.js

feat(lavin): better output

---

scripts/bitbucket-status.js

Los posibles colores son verde (sin incidencias), amarillo (minor), naranjo (major) y rojo (critical):

Se mejora el output con slack attachments

---

scripts/pegas.js
test/html/pegas-200.html
test/pegas.test.js

fix(js): new markup, changed cheerio scrap

---

scripts/tupoto.js

1. Changed request url (https://tupo.to/ ->
https://tupo.to/.netlify/functions.post)
2. Added "referer: https://tupo.to/" header to the request that fetchs
the url.
Test with 
```
npm run dev
huemul tupoto https://devschile.cl
```

Changed request url and added header

---

scripts/lavin.js

Se agrega imagen, si es que posee

---

scripts/awesome.js
scripts/ephemeral.js

En slack:
En terminal:
```
Hubot> hubot awesome backend
Hubot> En Awesome devsChile para #backend tenemos los siguientes links:
- crontab.guru (https://crontab.guru/): An easy to use editor for crontab schedules.
- dokku (http://dokku.viewdocs.io/dokku/): Minimal but very functional PASS implementation with heroku build pack and native docker support.
- hadolint (https://github.com/hadolint/hadolint): A smarter Dockerfile linter that helps you build best practice Docker images.
- Node.js Best Practices (https://github.com/i0natan/nodebestpractices): Node.js Best Practices
- Storj (https://storj.io/): Decentralized Cloud Storage
- Bash Commands and Tips (https://dev.to/awwsmm/101-bash-commands-and-tips-for-beginners-to-experts-30je): 101 Bash Commands and Tips for Beginners to Experts
- …
```

Se mejora salida de awesome

---

scripts/horario-verano

test:
```
huemul horario verano inicio
huemul horario verano fin
```
`huemul> :alarm_clock: El horario de verano este 2019 termina el sábado 06-04-2019`

new(script): huemul responds end/begin summertime

---

package.json
scripts/dameunatarjeta.js
scripts/uoct-golden.js
test/dameunatarjeta.test.js
test/uoct-golden.test.js
yarn.lock

fix(uoct) updated events JSON source for new UOCT website structure

---

scripts/como-donar.js

Se mejora el output del script como-donar

---

package.json
scripts/karma.js
test/karma.test.js
yarn.lock

Debería arreglar el no poder agregar karma a los usuarios nuevos, además de mostrar los nombres actualizados cuando corresponde.

feat(karma): replace karma brain with slack api for user search

---

package.json
scripts/karma.js
test/karma.test.js
yarn.lock

No se estaban obteniendo todos los usuarios porque Slack pagina los resultados de users.list.

Fix user list

---

.github/PULL_REQUEST_TEMPLATE/new-script.md

La idea es estandarizar la forma de contribuir y simplificar ese proceso. La cabecera de la plantilla no estoy seguro que funciona, ya que esta sintaxis solo la he visto en plantillas de issues.

Se agrega plantilla para PRs de nuevos scripts

---

scripts/uoct-golden.js
test/uoct-golden.test.js

Ademas se capturan respuestas invalidas desde el sitio a consultar.

Se cambia url a transporteinforma.cl en script uoct

---

test/uoct-golden.test.js

Se mejora la espera de los mocks de cada request. Esto propone solucionar el bug #604

Se mejora test de uoct

---

CODEOWNERS
scripts/fintual.js

Consulta la rentabilidad de los distintos fondos en la AGF Fintual
```
> huemul fintual risky norris
>RISKY NORRIS: Si hubieras invertido *$100.000* 
-Hace un año, hoy tendrías: *$136.000*(36.00%) :patrones: 
- Hace 6 meses, hoy esas 100 lucas serían *$110.000*(10.00%) :chart_with_upwards_trend: 
- Hace un mes esas luquitas hoy serían *$98.000*(-2.00%) :gonzaleee:
```

New command for fintual funds

---

scripts/iii.js

Se cambia el comando de ayuda para el Bot. Así no aparece duplicado y no se agregan cosas innecesarias cuando se realiza el `huemul help`
N/A

Update command iii

---

scripts/nasa.js

Se cambia el comando de ayuda para el Bot. Asi no aparece duplicado.
N/A

Update command foto del dia

---

scripts/covid19.js

Se agrega pais opcional a covid19 y lastUpdated
CLI
```
> huemul coronavirus
> Hay 238 casos confirmados, 0 recuperados y 0 muertes en Chile.
Last updated: marzo 18 2:33 PM
> huemul coronavirus china
> Hay 81102 casos confirmados, 69755 recuperados y 3241 muertes en china.
Last updated: marzo 18 1:13 PM
```

feat(scripts): Add country selection to covid19 and lastUpdated

---

scripts/dameunatarjeta.js
test/html/dameunatarjeta-200.html

El sitio usado para hacer el scrapping ha actualizado el layout del html, provocando con esto que el script deje de funcionar.
Se actualiza el scrapping para buscar en el nuevo layout.

fix(dameunatarjeta): se corrige scrapping

---

scripts/proximo-feriado.js

test: `huemul proximo feriado`
result: `El próximo feriado es el *Viernes 10 de Abril*, quedan *7*
días. Se celebra: Viernes Santo (_religioso_).`

fix(js): new endpont and changes y return structure

---

scripts/dameunpinned.js
scripts/saluda.js

Se necesita cambiar el nombre del canal Hardware a diy

Change name hardware to diy

---

scripts/proximo-feriado.js

Además de mostrar el siguiente feriado, en caso de caer un fin de semana agrega el siguiente feriado entre semana para que los :gonzaleee: tengamos un apice de esperanza.
```
> hubot proximo feriado
> El próximo feriado es el *Domingo 25 de Octubre*, quedan *12* días. Se celebra: Elecciones Municipales (_civil_).
El próximo feriado para los :gonzaleee: es el *Martes 8 de Diciembre*, quedan *12* días. Se celebra: Inmaculada Concepción (_religioso_).
```

feat: add support to work-day holidays for the gonzalee

---

scripts/horoscopo.js

Cambio de API para seguir funcionando el script
```
huemul> huemul horoscopo aries
huemul> 
Horóscopo de 16 octubre para Aries:
· Amor 💖 : Busque solucionar las cosas antes estas se agraven mucho más.
· Salud 🤕 : Jugar con su salud como una ruleta rusa no es lo más prudente. Quédate en casa y lávate bien las manos. Cuidemos juntos la salud de tod@s.
· Dinero 💰 : Las cosas se irán dando para que pueda dar inicio a su emprendimiento.
· Color 🖌 : Blanco.
· Número 🔢 : 12.
```

fix(api): nueva api para horoscopos funcionando

---

scripts/horoscopo.js
scripts/uoct-golden.js
test/uoct-golden.test.js

Se mejora output de formato de fecha y algunas otras cosillas de texto
Ejemplo:
```
huemul> huemul uoct
huemul> Encontrados 30 resultados :bomb::fire:
· 16/10/2020 14:35: Cierran perímetro en el centro de La Florida para privilegiar tránsito peatonal. Afecta inmediaciones de Mall Plaza Vespucio
· 16/10/2020 11:13: CERRADOS accesos a "Mapocho Ciclo Parque" en ribera de río por aumento del caudal.
· 16/10/2020 09:44: Este fin de semana (17 y 18 de octubre) se cerrará Vasco de Gama con Américo Vespucio por obras de construcción del colector de aguas lluvia.
...
```

feat(date): better format output

---

scripts/gold.js

Texto de script gold estaba desactualizado, ya no es sostenible durante la pandemia ir al correo seguido. El texto genérico da para entregar mejor solucion de entrega de swags (aparte de stickers) a quienes donan

chore(text): update text for gold script

---

scripts/plebiscito.js
scripts/plebiscito2020.js

Muestra la resultados parciales del plesbiscito 2020
Ejemplo:
```
> huemul plebiscito
> Preguntandole al servel...
Apruebo: 0% con 0 votos :huemul-matapacos:
Rechazo: 0% con 0 votos :chaleco-amarillo:
```

feat: add results for the plebiscito

---

scripts/plebiscito2020.js

Números con mejor formato, y Slack tb.
```
huemul> huemul plebiscito
huemul> Consultando al Servel :loading:
*Apruebo*: 77,50% con 1.001.157 votos :huemul-matapacos:
*Rechazo*: 22,50% con 290.668 votos :chaleco-amarillo:
```

feat(format): better output and count format

---

scripts/proximo-feriado.js

Ahora compara el dia si es workday para los :gonzalee: incluyendo el viernes, no solo comparando si es menor a.
```
$ huemul> huemul proximo feriado
$ huemul> El próximo feriado es el *Martes 8 de Diciembre*, quedan *19 días*. Se celebra: *Inmaculada Concepción (_religioso_)*
```

fix(workday): now calculates holiday in workday if it is in friday

---

package.json
scripts/impuestos.js
yarn.lock

El script te pide tu sueldo bruto mensual y te dice cuanto tienes que pagarle al SII por impuestos y cotizaciones. Un resumen de lo que aparece en https://impuestos.netlify.app/
```
huemul > huemul impuestos 2800000
huemul > Tendrás que pagar ~ *$2.763.125* :patrones:
- A favor tienes tu retención de boletas (10.75%): *$3.612.000*
- En contra tienes los impuestos (*$937.301*) y las cotizaciones (*$5.437.824*)
- Si optas por modalidad parcial, recibirás una devolución de ~ *$572.683*
```

feat: adds a script to calculate taxes & contributions

---

scripts/santoral.js

removed scrapping from La Segunda (buggy), now script reads directly from static JSON: https://gist.github.com/juanbrujo/c27f9bea0f5a7ac56802122ec50d5a9b
test: `huemul santoral`
> Hoy *domingo 24 de enero* el santoral es *Francisco de Sales* :angel:

fix(data): removed scrapping, get data from raw json

---

scripts/neeks.js
test/neeks.test.js

Complete redesign of neeks search UI. 
- Products were found, scraping is done in PLP (Product Listing Page)
- Single product found, redirects to PDP (Product Detail Page), and scraping is done from the product page.
- No results were found
- Product thumbnail
- Add to cart button
- Filter products out of stock
- Discount detection (and display) with price recalculation based on normal price (shown with strikethrough).
- Products are hard-limited to 10 results due to Block API limitations (TODO: limit as a parameter?)
Multiple results (scraping from PLP)
Multiple results with recalculated discounted price on some products.
Single result with recalculated discounted price (scraping from PDP)
No results (or single result with scraping from PDP with no stock)

Neeks: Complete UI redesign (Block Kit API)

---

scripts/poll.js
scripts/steam.js

Refactor/steam UI image url

---

scripts/steam.js

Refactor/steam UI remove loading msg

---

scripts/pegas.js

refactor(pegas): single api call per job

---

scripts/pegas.js

Adds "Remoto en <zone>" when remoteModality is remote_local (previously there was a hardcoded string)

refactor(pegas): remote zone added

---

scripts/nasa.js
scripts/sosearch.js

Mejor output del script
test: `$ huemul sosearch javascript OOP`
Closes #574

style: estaba feo ahora mejoró un poco

---

package.json
scripts/proximo-feriado.js
test/proximo-feriado.test.js
yarn.lock

Algunas veces el script the feriados mostraba de forma incorrecta el siguiente feriado cuando el más cercano es un fin de semana. Aproveché para hacer un refactor para que sea más facil de entender ademas de un test básico (hacer tests con ava es horrible. -- para todos! 😡).
Por último, cuando el dia cuando se usa el script es un feriado, ahora va a mostrar el siguiente.

fix(proximo-feriado): fix showing the wrong gonzales' holiday

---

package.json
scripts/karma.js
yarn.lock

El test `karma.test.js` probablemente está roto porque tiene mockeada la implementación anterior.

@here fixing huemul karma

---

scripts/proverbio-chino.js

Obtiene aleatoriamente un proverbio chino desde un documento CSV en Google Spreadsheets. Puede ser en:
* Inglés
* Chino (caracteres chinos)
* Pinyín (transliteración a caracteres latinos + explicación por caracter)
* `CNPROVERB_GSHEET_ID`
* `CNPROVERB_GSHEET_API_KEY`

feat(proverbios-chinos): añade script para obtener proverbios chinos

---

scripts/bin-checker.js

Obtiene códigos BIN de tarjetas de bancos en Chile.
Closes #701

feat(bin cl): agrega script para obtener códigos bin por banco chileno

---

scripts/beneficios-devschile.js

Lista beneficios para la comunidad.
closes #705

feat(beneficios): agrega script con beneficios para la comunidad

---

scripts/iqair.js

Se conecta a la API de [IQ Air ](https://www.iqair.com/) para saber la calificación y cantidad de contaminación usando el [AQI es Estados Unidos](https://www.weather.gov/safety/airquality-aqindex).

feat(aqiair): add script to gather current air quality stats

---

scripts/iqair.js

Agregar mas ciudades a iqair script

feat(iqair): add more cities

---

scripts/iqair.js

Agrega nuevas ciudades al script de calidad de aire.

fix(iqair): update cities

---

scripts/torrent.js
test/torrent.test.js

`.ag => .mx`
Fix por cambio de dominio

fix: new domain for YTS API

---

scripts/torrent.js
test/torrent.test.js

Updated torrent.js output test
